# Generated by Django 4.1.1 on 2022-09-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woodwork', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinstance',
            name='client',
        ),
    ]
