# Generated by Django 4.1.1 on 2022-09-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodwork', '0002_remove_productinstance_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Užsakoma'), ('t', 'Užsakyta'), ('g', 'Galima užsakyti'), ('r', 'Rezervuota')], default='a', help_text='Statusas', max_length=1),
        ),
    ]
