# Generated by Django 4.1.1 on 2022-09-27 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woodwork', '0003_alter_productinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='woodwork.colour'),
        ),
    ]
