# Generated by Django 4.1.1 on 2022-09-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodwork', '0004_alter_product_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='Example'),
        ),
    ]
