# Generated by Django 4.1.1 on 2022-09-28 16:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('woodwork', '0005_product_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='colour',
            name='visual',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='Example'),
        ),
        migrations.AlterField(
            model_name='colour',
            name='colour',
            field=models.CharField(max_length=100, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(blank=True, help_text='Short wardrobe description', max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ManyToManyField(help_text='Please select type for this wardrobe', to='woodwork.type'),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='due_back',
            field=models.DateField(blank=True, null=True, verbose_name='Will be available to order'),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique IO for wardrobe copy', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('b', 'Being orderred'), ('o', 'Orderred'), ('c', 'Can be orderred'), ('r', 'Reserved')], default='a', help_text='Status', max_length=1),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(help_text='Enter type of wardrobe (e.g. Bedroom wardrobe)', max_length=200, verbose_name='Type'),
        ),
    ]
