# Generated by Django 4.1.1 on 2022-09-29 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('woodwork', '0006_colour_visual_alter_colour_colour_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstance',
            name='requestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
