# Generated by Django 4.1.1 on 2022-09-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodwork', '0007_productinstance_requestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'Orderred'), ('c', 'Can be orderred')], default='a', help_text='Status', max_length=1),
        ),
    ]
