# Generated by Django 4.1.1 on 2022-09-29 15:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('woodwork', '0008_alter_productinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=tinymce.models.HTMLField(),
        ),
    ]
