# Generated by Django 4.1.1 on 2022-09-29 20:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('woodwork', '0010_wardrobereview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WardrobeReview',
            new_name='ProductReview',
        ),
    ]
