# Generated by Django 4.1.1 on 2022-10-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodwork', '0012_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'Orderred'), ('c', 'Can be orderred')], default='o', help_text='Status', max_length=1),
        ),
    ]
