# Generated by Django 4.1.1 on 2022-10-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodwork', '0013_alter_productinstance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstance',
            name='requirements',
            field=models.TextField(blank=True, help_text='Enter the date till when you would like to have the wardrobe ready and any other requirements (e.g. size, different colour, your city)', max_length=2000, null=True, verbose_name='Your notes for us'),
        ),
    ]
