# Generated by Django 4.1.1 on 2022-10-03 12:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('woodwork', '0014_productinstance_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstance',
            name='requirements',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Enter the date till when you would like to have the wardrobe ready and any other requirements (e.g. size, different colour, your city)', max_length=2000, null=True, verbose_name='Your notes for us'),
        ),
    ]
