# Generated by Django 4.1.1 on 2022-10-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodwork', '0015_alter_productinstance_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstance',
            name='due_back',
            field=models.DateField(blank=True, null=True, verbose_name='Last order completed on'),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'Orderred'), ('c', 'Can be orderred')], default='c', help_text='Status', max_length=1),
        ),
    ]
